### ISSUE TITLE
Running vraGetDeployment fails

### ISSUE THREAD

**Issue by DevOpsDCC** [prydin/vrealize-automation-plugin-for-jenkins#7]
I have tried multiple combinations for deploymentName and deploymentId
Neither seems to work.
When using the timeout parameter I get a warning.

With timeout flag

deploymentDetails = vraGetDeployment(
deploymentName: 'Jenkins-Tito-51fe30d4-8b84-45f4-884e-ffc46c208574',
timeout: 300
)

WARNING: Unknown parameter(s) found for class type 'com.vmware.vra.jenkinsplugin.pipeline.GetDeploymentStep': timeout
com.vmware.vra.jenkinsplugin.vra.VRAException: Expected 1 item, got 0
	at com.vmware.vra.jenkinsplugin.vra.VraApi.checkResponseSingleton(VraApi.java:98)
	at com.vmware.vra.jenkinsplugin.vra.VraApi.getCatalogDeploymentByName(VraApi.java:214)
	at com.vmware.vra.jenkinsplugin.pipeline.DeploymentAwareStep.resolveDeploymentId(DeploymentAwareStep.java:64)
	at com.vmware.vra.jenkinsplugin.pipeline.GetDeploymentExecution.run(GetDeploymentExecution.java:46)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE

Without Timeout flag
deploymentDetails = vraGetDeployment(
deploymentName: 'Jenkins-Tito-51fe30d4-8b84-45f4-884e-ffc46c208574',
//timeout: 300
)

com.vmware.vra.jenkinsplugin.vra.VRAException: Expected 1 item, got 0
	at com.vmware.vra.jenkinsplugin.vra.VraApi.checkResponseSingleton(VraApi.java:98)
	at com.vmware.vra.jenkinsplugin.vra.VraApi.getCatalogDeploymentByName(VraApi.java:214)
	at com.vmware.vra.jenkinsplugin.pipeline.DeploymentAwareStep.resolveDeploymentId(DeploymentAwareStep.java:64)
	at com.vmware.vra.jenkinsplugin.pipeline.GetDeploymentExecution.run(GetDeploymentExecution.java:46)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE

**Comment by prydin** [comment]
I'll have a look!

**Comment by prydin** [comment]
The timeout parameter is not supported for this step since it's supposed to return immediately.

As for finding the deployment, his works fine for me. Are you ABSOLUTELY sure you spelled the name correctly?

```
node {
    dep = vraGetDeployment(
        deploymentName: 'Is this accessible from Jenkins?', 
        vraURL: 'https://api.mgmt.cloud.vmware.com')
    print dep
}
```

**Comment by DevOpsDCC** [comment]
I have set the URL and token in the global params
The steps I am running are:


  1.  vraDeployFromCatalog – this works no issues environment is deployed
  2.  vraGetDeployment – I tried a more simplified name that does exist in vRA to see if it was a naming issue special characters etc.

As an FYI – I am running an on-premise version of vRA not cloud.
The version is 8.2
Could there be a difference in URL between cloud and on prem for the API to get deployments ?

This is my exact code for the step

        stage("Test Website") {
            steps {
                script {
                    echo "Get deployment information"
                    deploymentDetails = vraGetDeployment(
                        deploymentName: 'TITO'
                    )
                    echo "${deploymentDetails}"
                }
            }

Error
WARNING: Unknown parameter(s) found for class type 'com.vmware.vra.jenkinsplugin.pipeline.GetDeploymentStep': timeout
com.vmware.vra.jenkinsplugin.vra.VRAException: Expected 1 item, got 0
                at com.vmware.vra.jenkinsplugin.vra.VraApi.checkResponseSingleton(VraApi.java:98)
                at com.vmware.vra.jenkinsplugin.vra.VraApi.getCatalogDeploymentByName(VraApi.java:214)
                at com.vmware.vra.jenkinsplugin.pipeline.DeploymentAwareStep.resolveDeploymentId(DeploymentAwareStep.java:64)
                at com.vmware.vra.jenkinsplugin.pipeline.GetDeploymentExecution.run(GetDeploymentExecution.java:46)
                at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
                at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE


Daniel Clydesdale-Cotter

**Comment by DevOpsDCC** [comment]
I can access deployments via the rest API of vRA through this URL

https://my-server/deployment/api/deployments

This lists all deployments but can be targeted based on ID.

Daniel Clydesdale-Cotter

From: Daniel Clydesdale-Cotter<mailto:danielccotter@hotmail.com>
Sent: Wednesday, November 4, 2020 2:25 PM
To: prydin/vrealize-automation-plugin-for-jenkins<mailto:reply@reply.github.com>
Subject: RE: [prydin/vrealize-automation-plugin-for-jenkins] Running vraGetDeployment fails (#7)

I have set the URL and token in the global params
The steps I am running are:


  1.  vraDeployFromCatalog – this works no issues environment is deployed
  2.  vraGetDeployment – I tried a more simplified name that does exist in vRA to see if it was a naming issue special characters etc.

As an FYI – I am running an on-premise version of vRA not cloud.
The version is 8.2
Could there be a difference in URL between cloud and on prem for the API to get deployments ?

This is my exact code for the step

        stage("Test Website") {
            steps {
                script {
                    echo "Get deployment information"
                    deploymentDetails = vraGetDeployment(
                        deploymentName: 'TITO'
                    )
                    echo "${deploymentDetails}"
                }
            }

Error
WARNING: Unknown parameter(s) found for class type 'com.vmware.vra.jenkinsplugin.pipeline.GetDeploymentStep': timeout
com.vmware.vra.jenkinsplugin.vra.VRAException: Expected 1 item, got 0
                at com.vmware.vra.jenkinsplugin.vra.VraApi.checkResponseSingleton(VraApi.java:98)
                at com.vmware.vra.jenkinsplugin.vra.VraApi.getCatalogDeploymentByName(VraApi.java:214)
                at com.vmware.vra.jenkinsplugin.pipeline.DeploymentAwareStep.resolveDeploymentId(DeploymentAwareStep.java:64)
                at com.vmware.vra.jenkinsplugin.pipeline.GetDeploymentExecution.run(GetDeploymentExecution.java:46)
                at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
                at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE


Daniel Clydesdale-Cotter

**Comment by DevOpsDCC** [comment]
Should I create a direct API call to get this data?
I can get there from POSTMAN, is there API access in your plugin that would allow me to use the authentication but create my own GET/POST calls?

**Comment by prydin** [comment]
@DevOpsDCC The only thing I can think of is that the deployment isn't visible to your Jenkins pipeline due to user restrictions. Are you authenticating as the same user for Jenkins as you are when you're looking at it in the UI?

**Comment by DevOpsDCC** [comment]
I will triple check - the api access is coming from the configadmin local administrator who would normally have access to everything.

I will let you know once I have tested.

Daniel Clydesdale-Cotter
________________________________

**Comment by prydin** [comment]
Do you know how to list all deployments using Postman? I would try that with the configadmin user and see if the deployment is there.

**Comment by DevOpsDCC** [comment]
The deployment is there when using postman, I am going to try another couple of tests to see if I can see why nothing is coming back

Daniel Clydesdale-Cotter

**Comment by prydin** [comment]
You may also want to check if you can look it up using the ID in a Jenkins pipeline. (You can obtain the ID from the Postman output)

**Comment by DevOpsDCC** [comment]
Unfortunately this doesn’t work either

                    echo "Get deployment information"
                    deploymentDetails = vraGetDeployment(
                        deploymentId: '7e79f6c8-38ae-4f2a-9bff-adedac2a5fda'
                    )
                    echo "${deploymentDetails}"

Daniel Clydesdale-Cotter

**Comment by DevOpsDCC** [comment]
A curl command from the command line on the Jenkins server also pulls back the info that postman does.
I am at a loss at this point!

curl --insecure --location --request GET 'https://prod-vra.ad.echostor.com/deployment/api/deployments/' --header 'Content-Type: application/json' --header 'Authorization: Bearer SecretToken'

Daniel Clydesdale-Cotter

From: Daniel Clydesdale-Cotter<mailto:danielccotter@hotmail.com>
Sent: Tuesday, November 10, 2020 10:06 AM
To: prydin/vrealize-automation-plugin-for-jenkins<mailto:reply@reply.github.com>; prydin/vrealize-automation-plugin-for-jenkins<mailto:vrealize-automation-plugin-for-jenkins@noreply.github.com>
Cc: Mention<mailto:mention@noreply.github.com>
Subject: RE: [prydin/vrealize-automation-plugin-for-jenkins] Running vraGetDeployment fails (#7)

Unfortunately this doesn’t work either

                    echo "Get deployment information"
                    deploymentDetails = vraGetDeployment(
                        deploymentId: '7e79f6c8-38ae-4f2a-9bff-adedac2a5fda'
                    )
                    echo "${deploymentDetails}"

Daniel Clydesdale-Cotter

**Comment by prydin** [comment]
Do you have multiple organizations?

**Comment by DevOpsDCC** [comment]
Single org I believe

Daniel Clydesdale-Cotter

**Comment by prydin** [comment]
There's clearly some contextual/environmental mismatch somewhere. The code for looking up a deployment by ID is trivial and should not fail that way.

Could you try to deploy something in a pipeline and then try to look it up right after? I tried the pipeline below. You'll obviously need to change the project name and catalog item name.

```groovy
node {
    def dep = vraDeployFromCatalog(
        catalogItemName: 'jenkins-test',
        count: 1,
        deploymentName: 'MyDeployment',
        projectName: 'JenkinsTest',
        reason: 'Test',
        timeout: 300,
        version: '2')
    def dep2 = vraGetDeployment(
        deploymentName: "MyDeployment")
    print dep2
}
```

**Comment by DevOpsDCC** [comment]
That does work!
So I guess having the deployment and the get deployment details in different stages doesn’t work.

I will do more testing as I feel like it shouldn’t matter where the vraGetDeployment is executed form a stage perspective.

Here is my code that just worked as an FYI

Thank you for helping me out!

// Define Variables to use across stages
deployment = ''
deploymentName = ''
deploymentId = ''
deploymentDetails = ''

pipeline {
    agent any
    stages {
        stage("Build Infrastructure") {
            steps {
                script {
                    echo "Building Infrastructure and deploying code"
                    deployment = vraDeployFromCatalog(
                        catalogItemName: 'Monolith Tito',
                        count: 1,
                        deploymentName: 'Jenkins-Test',
                        projectName: 'TITO',
                        reason: 'Build Infra for testing',
                        timeout: 1200,
                        version: '1.24',
                        inputs: ''
                        )
                    assert deployment != null
                    deploymentDetails = vraGetDeployment(
                        deploymentName: "Jenkins-Test"
                    )
                    print deploymentDetails
                }
            }
        }
        stage(".
        ")
    }
}

Daniel Clydesdale-Cotter

**Comment by DevOpsDCC** [comment]
I think I found the issue.
When you start the build from a specific stage in the pipeline it doesn’t seem to connect and I get the error.

However if the build is run from scratch in a new build the vragetDeployment works fine in any stage of the pipeline.

Working code

// Define Variables to use across stages
deployment = ''
deploymentName = ''
deploymentId = ''
deploymentDetails = ''

pipeline {
    agent any
    stages {
        stage("Build Infrastructure") {
            steps {
                script {
                    deploymentDetails = vraGetDeployment(
                        deploymentName: "TITO"
                    )
                    print deploymentDetails
                }
            }
        }
        stage("Test Website") {
            steps {
                script {
                    deploymentDetails = vraGetDeployment(
                        deploymentName: "TITO"
                    )
                    print deploymentDetails
                }
            }
        }
    }
}

Daniel Clydesdale-Cotter

From: Daniel Clydesdale-Cotter<mailto:danielccotter@hotmail.com>
Sent: Tuesday, November 10, 2020 11:50 AM
To: prydin/vrealize-automation-plugin-for-jenkins<mailto:reply@reply.github.com>; prydin/vrealize-automation-plugin-for-jenkins<mailto:vrealize-automation-plugin-for-jenkins@noreply.github.com>
Cc: Mention<mailto:mention@noreply.github.com>
Subject: RE: [prydin/vrealize-automation-plugin-for-jenkins] Running vraGetDeployment fails (#7)

That does work!
So I guess having the deployment and the get deployment details in different stages doesn’t work.

I will do more testing as I feel like it shouldn’t matter where the vraGetDeployment is executed form a stage perspective.

Here is my code that just worked as an FYI

Thank you for helping me out!

// Define Variables to use across stages
deployment = ''
deploymentName = ''
deploymentId = ''
deploymentDetails = ''

pipeline {
    agent any
    stages {
        stage("Build Infrastructure") {
            steps {
                script {
                    echo "Building Infrastructure and deploying code"
                    deployment = vraDeployFromCatalog(
                        catalogItemName: 'Monolith Tito',
                        count: 1,
                        deploymentName: 'Jenkins-Test',
                        projectName: 'TITO',
                        reason: 'Build Infra for testing',
                        timeout: 1200,
                        version: '1.24',
                        inputs: ''
                        )
                    assert deployment != null
                    deploymentDetails = vraGetDeployment(
                        deploymentName: "Jenkins-Test"
                    )
                    print deploymentDetails
                }
            }
        }
        stage(".
        ")
    }
}

Daniel Clydesdale-Cotter
